config/routes.rb
PushServer::Application.routes.draw do
  resources :devices

  match 'devices/:id/push' => 'devices#push', :as => :push

end

app/models/device.rb
class Device < ActiveRecord::Base
  validates_uniqueness_of :mobile_uuid

  def push
    c2dm = C2DM::Push.new("sorensonapp@gmail.com", "4sorenson", "TestApp")
    c2dm.send_notification(registration_id, "Hello World")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @devices }
    end
  end

  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to(@device, :notice => 'Device was successfully created.') }
        format.json  { render :json => @device, :status => :created, :location => @device }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @device = Device.find_by_mobile_uuid(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(devices_url) }
      format.json  { head :ok }
    end
  end

  def push
    @device = Device.find(params[:id])
    @device.push

    respond_to do |format|
      format.html { redirect_to(devices_url) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :registration_id %><br />
    <%= f.text_field :registration_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Device Type</th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.device_type %></td>
    <td><%= button_to 'Push to Device', push_path(device) %></td>
    <td><%= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @device.type %>
</p>

<p>
  <b>Registration:</b>
  <%= @device.registration_id %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PushServer</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>